/*
 * This source file was generated by the Gradle 'init' task
 */
package exercises.capinterview;

import java.util.logging.Logger;

public class Main {
    private static final Logger logger = Logger.getLogger(Main.class.getName());

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        logger.info(new Main().getGreeting());
    }
}