/*
 * This source file was generated by the Gradle 'init' task
 */
package exercises2capinterview;


import java.util.List;

public class Main {
    public static void main(String[] args) {
        UserDao userDao = new UserDaoImpl();

        // Adding a new user
        User newUser = new User(0, "John Doe", "johndoe@example.com");
        userDao.addUser(newUser);

        // Fetching all users
        List<User> users = userDao.getAllUsers();
        for (User user : users) {
            System.out.println(user);
        }

        // Fetching a specific user by ID
        User user = userDao.getUser(1);
        System.out.println("Fetched user: " + user);

        // Updating a user
        if (user != null) {
            user.setName("John Updated");
            userDao.updateUser(user);
        }

        // Deleting a user
        userDao.deleteUser(2);
    }
}
